CREATE TABLE IF NOT EXISTS Genre (
	Genre_ID SERIAL PRIMARY KEY,
	Genre_Name VARCHAR(60) NOT NULL
	);
	
CREATE TABLE IF NOT EXISTS Performer (
	Performer_ID SERIAL PRIMARY KEY,
	Performer_Name VARCHAR(60) NOT NULL,
	Genre_ID INTEGER NOT NULL REFERENCES Genre(Genre_ID)
	);

CREATE TABLE IF NOT EXISTS Genres_Performers (
	Genre_ID INTEGER REFERENCES Genre(Genre_ID),
	Performer_ID INTEGER REFERENCES Performer(Performer_ID),
	CONSTRAINT pkgp PRIMARY KEY (Genre_ID, Performer_ID)
	);

CREATE TABLE IF NOT EXISTS Album (
	Album_ID SERIAL PRIMARY KEY,
	Album_Name VARCHAR(60) NOT NULL,
	Year_Edition INTEGER NOT NULL,
	Performer_ID INTEGER NOT NULL REFERENCES Performer(Performer_ID)
	);

CREATE TABLE IF NOT EXISTS Performers_Albums (
	Performer_ID INTEGER REFERENCES Performer(Performer_ID),
	Album_ID INTEGER REFERENCES Album(Album_ID),
	CONSTRAINT pkpa PRIMARY KEY (Performer_ID, Album_ID)
	);

CREATE TABLE IF NOT EXISTS Song (
	Song_ID SERIAL PRIMARY KEY,
	Song_Name VARCHAR(60) NOT NULL,
	Duration TIME NOT NULL,
	Album_ID INTEGER NOT NULL REFERENCES Album(Album_ID)
	);

CREATE TABLE IF NOT EXISTS Collection (
	Collection_ID SERIAL PRIMARY KEY,
	Collection_Name VARCHAR(60) NOT NULL,
	Year_Edition INTEGER NOT NULL,
	Song_ID INTEGER NOT NULL REFERENCES Song(Song_ID)
	);